### ISSUE TITLE
CapstonCode Review

### ISSUE THREAD

**Issue by Felipe-Perez-Ferraro** [mahammad-mostafa/game-industry-conference#2]
- Hi! I think your code is really great, the use of HTML semantic tags to improve the seo and make your website more readable its perfect, about your CSS code nothing to say! You have very well structured your code and stylings. Finally the Javascript code its okay too, the navbar menu, the speakers dispay and the expand menu its very good.
I kindly recommend to add the hover to the main program section.

**Comment by mahammad-mostafa** [comment]
Thank you @Felipe-Perez-Ferraro for your feedback. I have successfully resolved the issue and uploaded the fix.
